version: "2"

formatters:
  settings:
    gci:
      sections:
        - standard # Standard section: captures all standard packages.
        - default # Default section: contains all imports that could not be matched to another section type.
        - prefix(github.com/a-novel-kit)
        - prefix(github.com/a-novel)
        - prefix(github.com/a-novel/service-story-schematics)

linters:
  default: all
  disable:
    - depguard
    - dupl
    - exhaustruct
    - varnamelen
    - revive
    - ireturn
    - gochecknoinits
    - gochecknoglobals
    - iface
    - funlen
    - funcorder
    - cyclop
    - err113
    - contextcheck # Conflicts with Sentry context propagation.

  settings:
    gosec:
      excludes:
        - G115
    tagliatelle:
      case:
        rules:
          json: goCamel
          yaml: goCamel

  exclusions:
    paths:
      - mocks
    rules:
      - path: (.+)_test.go
        linters:
          - err113
          - forcetypeassert
          - maintidx
          - gocognit
          - tagliatelle
          - cyclop
          - gosec
      # DAO behaves poorly in parallel testing, mainly because each test is done concurrently using its own transaction.
      - path: dao/(.+)_test.go
        linters:
          - tparallel
          - paralleltest
      - path: daoai/(.+)_test.go
        linters:
          - tparallel
          - paralleltest
      - path: cmd/api/(.+)_test.go
        linters:
          - tparallel
          - paralleltest
