packages:
  github.com/a-novel/service-story-schematics/internal/services:
    config:
      all: true
      pkgname: servicesmocks
      dir: internal/services/mocks
      filename: mocks.go
  github.com/a-novel/service-story-schematics/internal/api:
    config:
      all: true
      pkgname: apimocks
      dir: internal/api/mocks
      filename: mocks.go
