beat:
  description: |
    A beat is a unit of story structure that represents a specific moment or event in the narrative.
  schema:
    type: object
    additionalProperties: false
    required:
      - key
      - title
      - content
    properties:
      key:
        type: string
        description: The json key of the given beat
      title:
        type: string
        description: A short title representing the beat
      content:
        type: string
        description: A summary of the scenes in the beat

beats:
  description: |
    A collection of beats that make up the story structure, based on the chosen story plan.
  schema:
    type: object
    additionalProperties: false
    required:
      - beats
    properties:
      beats:
        items:
          type: object
          additionalProperties: false
          required:
            - key
            - title
            - content
          properties:
            key:
              type: string
              description: The json key of the given beat
            title:
              type: string
              description: A short title representing the beat
            content:
              type: string
              description: A summary of the scenes in the beat

logline:
  description: |
    A logline is a one-sentence summary of a story that captures its essence and hooks the reader's interest.
  schema:
    type: object
    additionalProperties: false
    required:
      - name
      - content
    properties:
      name:
        type: string
        description: The title of the story.
      content:
        type: string
        description: A short summary of the story.

loglines:
  description: |
    A collection of loglines that make up the story structure, based on the chosen story plan.
  schema:
    type: object
    additionalProperties: false
    required:
      - loglines
    properties:
      loglines:
        type: array
        items:
          type: object
          additionalProperties: false
          required:
            - name
            - content
          properties:
            name:
              type: string
              description: The title of the story.
            content:
              type: string
              description: A short summary of the story.
