// Code generated by mockery v2.53.1. DO NOT EDIT.

package servicesmocks

import (
	context "github.com/a-novel-kit/context"
	dao "github.com/a-novel/story-schematics/internal/dao"
	mock "github.com/stretchr/testify/mock"

	models "github.com/a-novel/story-schematics/models"
)

// MockCreateLoglineSource is an autogenerated mock type for the CreateLoglineSource type
type MockCreateLoglineSource struct {
	mock.Mock
}

type MockCreateLoglineSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateLoglineSource) EXPECT() *MockCreateLoglineSource_Expecter {
	return &MockCreateLoglineSource_Expecter{mock: &_m.Mock}
}

// InsertLogline provides a mock function with given fields: ctx, data
func (_m *MockCreateLoglineSource) InsertLogline(ctx context.Context, data dao.InsertLoglineData) (*dao.LoglineEntity, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for InsertLogline")
	}

	var r0 *dao.LoglineEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dao.InsertLoglineData) (*dao.LoglineEntity, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dao.InsertLoglineData) *dao.LoglineEntity); ok {
		r0 = rf(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.LoglineEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dao.InsertLoglineData) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCreateLoglineSource_InsertLogline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertLogline'
type MockCreateLoglineSource_InsertLogline_Call struct {
	*mock.Call
}

// InsertLogline is a helper method to define mock.On call
//   - ctx context.Context
//   - data dao.InsertLoglineData
func (_e *MockCreateLoglineSource_Expecter) InsertLogline(ctx interface{}, data interface{}) *MockCreateLoglineSource_InsertLogline_Call {
	return &MockCreateLoglineSource_InsertLogline_Call{Call: _e.mock.On("InsertLogline", ctx, data)}
}

func (_c *MockCreateLoglineSource_InsertLogline_Call) Run(run func(ctx context.Context, data dao.InsertLoglineData)) *MockCreateLoglineSource_InsertLogline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dao.InsertLoglineData))
	})
	return _c
}

func (_c *MockCreateLoglineSource_InsertLogline_Call) Return(_a0 *dao.LoglineEntity, _a1 error) *MockCreateLoglineSource_InsertLogline_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCreateLoglineSource_InsertLogline_Call) RunAndReturn(run func(context.Context, dao.InsertLoglineData) (*dao.LoglineEntity, error)) *MockCreateLoglineSource_InsertLogline_Call {
	_c.Call.Return(run)
	return _c
}

// SelectSlugIteration provides a mock function with given fields: ctx, data
func (_m *MockCreateLoglineSource) SelectSlugIteration(ctx context.Context, data dao.SelectSlugIterationData) (models.Slug, int, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for SelectSlugIteration")
	}

	var r0 models.Slug
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, dao.SelectSlugIterationData) (models.Slug, int, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dao.SelectSlugIterationData) models.Slug); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Get(0).(models.Slug)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dao.SelectSlugIterationData) int); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, dao.SelectSlugIterationData) error); ok {
		r2 = rf(ctx, data)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockCreateLoglineSource_SelectSlugIteration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectSlugIteration'
type MockCreateLoglineSource_SelectSlugIteration_Call struct {
	*mock.Call
}

// SelectSlugIteration is a helper method to define mock.On call
//   - ctx context.Context
//   - data dao.SelectSlugIterationData
func (_e *MockCreateLoglineSource_Expecter) SelectSlugIteration(ctx interface{}, data interface{}) *MockCreateLoglineSource_SelectSlugIteration_Call {
	return &MockCreateLoglineSource_SelectSlugIteration_Call{Call: _e.mock.On("SelectSlugIteration", ctx, data)}
}

func (_c *MockCreateLoglineSource_SelectSlugIteration_Call) Run(run func(ctx context.Context, data dao.SelectSlugIterationData)) *MockCreateLoglineSource_SelectSlugIteration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dao.SelectSlugIterationData))
	})
	return _c
}

func (_c *MockCreateLoglineSource_SelectSlugIteration_Call) Return(_a0 models.Slug, _a1 int, _a2 error) *MockCreateLoglineSource_SelectSlugIteration_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockCreateLoglineSource_SelectSlugIteration_Call) RunAndReturn(run func(context.Context, dao.SelectSlugIterationData) (models.Slug, int, error)) *MockCreateLoglineSource_SelectSlugIteration_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCreateLoglineSource creates a new instance of MockCreateLoglineSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateLoglineSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateLoglineSource {
	mock := &MockCreateLoglineSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
