// Code generated by mockery v2.53.1. DO NOT EDIT.

package servicesmocks

import (
	context "github.com/a-novel-kit/context"
	dao "github.com/a-novel/story-schematics/internal/dao"
	mock "github.com/stretchr/testify/mock"
)

// MockListLoglinesSource is an autogenerated mock type for the ListLoglinesSource type
type MockListLoglinesSource struct {
	mock.Mock
}

type MockListLoglinesSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListLoglinesSource) EXPECT() *MockListLoglinesSource_Expecter {
	return &MockListLoglinesSource_Expecter{mock: &_m.Mock}
}

// ListLoglines provides a mock function with given fields: ctx, data
func (_m *MockListLoglinesSource) ListLoglines(ctx context.Context, data dao.ListLoglinesData) ([]*dao.LoglinePreviewEntity, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for ListLoglines")
	}

	var r0 []*dao.LoglinePreviewEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dao.ListLoglinesData) ([]*dao.LoglinePreviewEntity, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dao.ListLoglinesData) []*dao.LoglinePreviewEntity); ok {
		r0 = rf(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dao.LoglinePreviewEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dao.ListLoglinesData) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockListLoglinesSource_ListLoglines_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListLoglines'
type MockListLoglinesSource_ListLoglines_Call struct {
	*mock.Call
}

// ListLoglines is a helper method to define mock.On call
//   - ctx context.Context
//   - data dao.ListLoglinesData
func (_e *MockListLoglinesSource_Expecter) ListLoglines(ctx interface{}, data interface{}) *MockListLoglinesSource_ListLoglines_Call {
	return &MockListLoglinesSource_ListLoglines_Call{Call: _e.mock.On("ListLoglines", ctx, data)}
}

func (_c *MockListLoglinesSource_ListLoglines_Call) Run(run func(ctx context.Context, data dao.ListLoglinesData)) *MockListLoglinesSource_ListLoglines_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dao.ListLoglinesData))
	})
	return _c
}

func (_c *MockListLoglinesSource_ListLoglines_Call) Return(_a0 []*dao.LoglinePreviewEntity, _a1 error) *MockListLoglinesSource_ListLoglines_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockListLoglinesSource_ListLoglines_Call) RunAndReturn(run func(context.Context, dao.ListLoglinesData) ([]*dao.LoglinePreviewEntity, error)) *MockListLoglinesSource_ListLoglines_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockListLoglinesSource creates a new instance of MockListLoglinesSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListLoglinesSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListLoglinesSource {
	mock := &MockListLoglinesSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
