// Code generated by mockery v2.53.1. DO NOT EDIT.

package servicesmocks

import (
	context "github.com/a-novel-kit/context"
	dao "github.com/a-novel/story-schematics/internal/dao"
	daoai "github.com/a-novel/story-schematics/internal/daoai"

	mock "github.com/stretchr/testify/mock"

	models "github.com/a-novel/story-schematics/models"

	uuid "github.com/google/uuid"
)

// MockRegenerateBeatsSource is an autogenerated mock type for the RegenerateBeatsSource type
type MockRegenerateBeatsSource struct {
	mock.Mock
}

type MockRegenerateBeatsSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRegenerateBeatsSource) EXPECT() *MockRegenerateBeatsSource_Expecter {
	return &MockRegenerateBeatsSource_Expecter{mock: &_m.Mock}
}

// RegenerateBeats provides a mock function with given fields: ctx, request
func (_m *MockRegenerateBeatsSource) RegenerateBeats(ctx context.Context, request daoai.RegenerateBeatsRequest) ([]models.Beat, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for RegenerateBeats")
	}

	var r0 []models.Beat
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, daoai.RegenerateBeatsRequest) ([]models.Beat, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, daoai.RegenerateBeatsRequest) []models.Beat); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Beat)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, daoai.RegenerateBeatsRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRegenerateBeatsSource_RegenerateBeats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegenerateBeats'
type MockRegenerateBeatsSource_RegenerateBeats_Call struct {
	*mock.Call
}

// RegenerateBeats is a helper method to define mock.On call
//   - ctx context.Context
//   - request daoai.RegenerateBeatsRequest
func (_e *MockRegenerateBeatsSource_Expecter) RegenerateBeats(ctx interface{}, request interface{}) *MockRegenerateBeatsSource_RegenerateBeats_Call {
	return &MockRegenerateBeatsSource_RegenerateBeats_Call{Call: _e.mock.On("RegenerateBeats", ctx, request)}
}

func (_c *MockRegenerateBeatsSource_RegenerateBeats_Call) Run(run func(ctx context.Context, request daoai.RegenerateBeatsRequest)) *MockRegenerateBeatsSource_RegenerateBeats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(daoai.RegenerateBeatsRequest))
	})
	return _c
}

func (_c *MockRegenerateBeatsSource_RegenerateBeats_Call) Return(_a0 []models.Beat, _a1 error) *MockRegenerateBeatsSource_RegenerateBeats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRegenerateBeatsSource_RegenerateBeats_Call) RunAndReturn(run func(context.Context, daoai.RegenerateBeatsRequest) ([]models.Beat, error)) *MockRegenerateBeatsSource_RegenerateBeats_Call {
	_c.Call.Return(run)
	return _c
}

// SelectBeatsSheet provides a mock function with given fields: ctx, data
func (_m *MockRegenerateBeatsSource) SelectBeatsSheet(ctx context.Context, data uuid.UUID) (*dao.BeatsSheetEntity, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for SelectBeatsSheet")
	}

	var r0 *dao.BeatsSheetEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*dao.BeatsSheetEntity, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *dao.BeatsSheetEntity); ok {
		r0 = rf(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.BeatsSheetEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRegenerateBeatsSource_SelectBeatsSheet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectBeatsSheet'
type MockRegenerateBeatsSource_SelectBeatsSheet_Call struct {
	*mock.Call
}

// SelectBeatsSheet is a helper method to define mock.On call
//   - ctx context.Context
//   - data uuid.UUID
func (_e *MockRegenerateBeatsSource_Expecter) SelectBeatsSheet(ctx interface{}, data interface{}) *MockRegenerateBeatsSource_SelectBeatsSheet_Call {
	return &MockRegenerateBeatsSource_SelectBeatsSheet_Call{Call: _e.mock.On("SelectBeatsSheet", ctx, data)}
}

func (_c *MockRegenerateBeatsSource_SelectBeatsSheet_Call) Run(run func(ctx context.Context, data uuid.UUID)) *MockRegenerateBeatsSource_SelectBeatsSheet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRegenerateBeatsSource_SelectBeatsSheet_Call) Return(_a0 *dao.BeatsSheetEntity, _a1 error) *MockRegenerateBeatsSource_SelectBeatsSheet_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRegenerateBeatsSource_SelectBeatsSheet_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*dao.BeatsSheetEntity, error)) *MockRegenerateBeatsSource_SelectBeatsSheet_Call {
	_c.Call.Return(run)
	return _c
}

// SelectLogline provides a mock function with given fields: ctx, data
func (_m *MockRegenerateBeatsSource) SelectLogline(ctx context.Context, data dao.SelectLoglineData) (*dao.LoglineEntity, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for SelectLogline")
	}

	var r0 *dao.LoglineEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dao.SelectLoglineData) (*dao.LoglineEntity, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dao.SelectLoglineData) *dao.LoglineEntity); ok {
		r0 = rf(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.LoglineEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dao.SelectLoglineData) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRegenerateBeatsSource_SelectLogline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectLogline'
type MockRegenerateBeatsSource_SelectLogline_Call struct {
	*mock.Call
}

// SelectLogline is a helper method to define mock.On call
//   - ctx context.Context
//   - data dao.SelectLoglineData
func (_e *MockRegenerateBeatsSource_Expecter) SelectLogline(ctx interface{}, data interface{}) *MockRegenerateBeatsSource_SelectLogline_Call {
	return &MockRegenerateBeatsSource_SelectLogline_Call{Call: _e.mock.On("SelectLogline", ctx, data)}
}

func (_c *MockRegenerateBeatsSource_SelectLogline_Call) Run(run func(ctx context.Context, data dao.SelectLoglineData)) *MockRegenerateBeatsSource_SelectLogline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dao.SelectLoglineData))
	})
	return _c
}

func (_c *MockRegenerateBeatsSource_SelectLogline_Call) Return(_a0 *dao.LoglineEntity, _a1 error) *MockRegenerateBeatsSource_SelectLogline_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRegenerateBeatsSource_SelectLogline_Call) RunAndReturn(run func(context.Context, dao.SelectLoglineData) (*dao.LoglineEntity, error)) *MockRegenerateBeatsSource_SelectLogline_Call {
	_c.Call.Return(run)
	return _c
}

// SelectStoryPlan provides a mock function with given fields: ctx, data
func (_m *MockRegenerateBeatsSource) SelectStoryPlan(ctx context.Context, data uuid.UUID) (*dao.StoryPlanEntity, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for SelectStoryPlan")
	}

	var r0 *dao.StoryPlanEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*dao.StoryPlanEntity, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *dao.StoryPlanEntity); ok {
		r0 = rf(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.StoryPlanEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRegenerateBeatsSource_SelectStoryPlan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectStoryPlan'
type MockRegenerateBeatsSource_SelectStoryPlan_Call struct {
	*mock.Call
}

// SelectStoryPlan is a helper method to define mock.On call
//   - ctx context.Context
//   - data uuid.UUID
func (_e *MockRegenerateBeatsSource_Expecter) SelectStoryPlan(ctx interface{}, data interface{}) *MockRegenerateBeatsSource_SelectStoryPlan_Call {
	return &MockRegenerateBeatsSource_SelectStoryPlan_Call{Call: _e.mock.On("SelectStoryPlan", ctx, data)}
}

func (_c *MockRegenerateBeatsSource_SelectStoryPlan_Call) Run(run func(ctx context.Context, data uuid.UUID)) *MockRegenerateBeatsSource_SelectStoryPlan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRegenerateBeatsSource_SelectStoryPlan_Call) Return(_a0 *dao.StoryPlanEntity, _a1 error) *MockRegenerateBeatsSource_SelectStoryPlan_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRegenerateBeatsSource_SelectStoryPlan_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*dao.StoryPlanEntity, error)) *MockRegenerateBeatsSource_SelectStoryPlan_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRegenerateBeatsSource creates a new instance of MockRegenerateBeatsSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRegenerateBeatsSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRegenerateBeatsSource {
	mock := &MockRegenerateBeatsSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
