// Code generated by mockery v2.53.1. DO NOT EDIT.

package apimocks

import (
	context "github.com/a-novel-kit/context"
	mock "github.com/stretchr/testify/mock"

	models "github.com/a-novel/story-schematics/models"

	services "github.com/a-novel/story-schematics/internal/services"
)

// MockListBeatsSheetsService is an autogenerated mock type for the ListBeatsSheetsService type
type MockListBeatsSheetsService struct {
	mock.Mock
}

type MockListBeatsSheetsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListBeatsSheetsService) EXPECT() *MockListBeatsSheetsService_Expecter {
	return &MockListBeatsSheetsService_Expecter{mock: &_m.Mock}
}

// ListBeatsSheets provides a mock function with given fields: ctx, request
func (_m *MockListBeatsSheetsService) ListBeatsSheets(ctx context.Context, request services.ListBeatsSheetsRequest) ([]*models.BeatsSheetPreview, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for ListBeatsSheets")
	}

	var r0 []*models.BeatsSheetPreview
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, services.ListBeatsSheetsRequest) ([]*models.BeatsSheetPreview, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, services.ListBeatsSheetsRequest) []*models.BeatsSheetPreview); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.BeatsSheetPreview)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, services.ListBeatsSheetsRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockListBeatsSheetsService_ListBeatsSheets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBeatsSheets'
type MockListBeatsSheetsService_ListBeatsSheets_Call struct {
	*mock.Call
}

// ListBeatsSheets is a helper method to define mock.On call
//   - ctx context.Context
//   - request services.ListBeatsSheetsRequest
func (_e *MockListBeatsSheetsService_Expecter) ListBeatsSheets(ctx interface{}, request interface{}) *MockListBeatsSheetsService_ListBeatsSheets_Call {
	return &MockListBeatsSheetsService_ListBeatsSheets_Call{Call: _e.mock.On("ListBeatsSheets", ctx, request)}
}

func (_c *MockListBeatsSheetsService_ListBeatsSheets_Call) Run(run func(ctx context.Context, request services.ListBeatsSheetsRequest)) *MockListBeatsSheetsService_ListBeatsSheets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(services.ListBeatsSheetsRequest))
	})
	return _c
}

func (_c *MockListBeatsSheetsService_ListBeatsSheets_Call) Return(_a0 []*models.BeatsSheetPreview, _a1 error) *MockListBeatsSheetsService_ListBeatsSheets_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockListBeatsSheetsService_ListBeatsSheets_Call) RunAndReturn(run func(context.Context, services.ListBeatsSheetsRequest) ([]*models.BeatsSheetPreview, error)) *MockListBeatsSheetsService_ListBeatsSheets_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockListBeatsSheetsService creates a new instance of MockListBeatsSheetsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListBeatsSheetsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListBeatsSheetsService {
	mock := &MockListBeatsSheetsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
