// Code generated by mockery v2.53.1. DO NOT EDIT.

package apimocks

import (
	context "github.com/a-novel-kit/context"
	mock "github.com/stretchr/testify/mock"

	models "github.com/a-novel/service-story-schematics/models"

	services "github.com/a-novel/service-story-schematics/internal/services"
)

// MockGenerateLoglinesService is an autogenerated mock type for the GenerateLoglinesService type
type MockGenerateLoglinesService struct {
	mock.Mock
}

type MockGenerateLoglinesService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGenerateLoglinesService) EXPECT() *MockGenerateLoglinesService_Expecter {
	return &MockGenerateLoglinesService_Expecter{mock: &_m.Mock}
}

// GenerateLoglines provides a mock function with given fields: ctx, request
func (_m *MockGenerateLoglinesService) GenerateLoglines(ctx context.Context, request services.GenerateLoglinesRequest) ([]models.LoglineIdea, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GenerateLoglines")
	}

	var r0 []models.LoglineIdea
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, services.GenerateLoglinesRequest) ([]models.LoglineIdea, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, services.GenerateLoglinesRequest) []models.LoglineIdea); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.LoglineIdea)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, services.GenerateLoglinesRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGenerateLoglinesService_GenerateLoglines_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateLoglines'
type MockGenerateLoglinesService_GenerateLoglines_Call struct {
	*mock.Call
}

// GenerateLoglines is a helper method to define mock.On call
//   - ctx context.Context
//   - request services.GenerateLoglinesRequest
func (_e *MockGenerateLoglinesService_Expecter) GenerateLoglines(ctx interface{}, request interface{}) *MockGenerateLoglinesService_GenerateLoglines_Call {
	return &MockGenerateLoglinesService_GenerateLoglines_Call{Call: _e.mock.On("GenerateLoglines", ctx, request)}
}

func (_c *MockGenerateLoglinesService_GenerateLoglines_Call) Run(run func(ctx context.Context, request services.GenerateLoglinesRequest)) *MockGenerateLoglinesService_GenerateLoglines_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(services.GenerateLoglinesRequest))
	})
	return _c
}

func (_c *MockGenerateLoglinesService_GenerateLoglines_Call) Return(_a0 []models.LoglineIdea, _a1 error) *MockGenerateLoglinesService_GenerateLoglines_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGenerateLoglinesService_GenerateLoglines_Call) RunAndReturn(run func(context.Context, services.GenerateLoglinesRequest) ([]models.LoglineIdea, error)) *MockGenerateLoglinesService_GenerateLoglines_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGenerateLoglinesService creates a new instance of MockGenerateLoglinesService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenerateLoglinesService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenerateLoglinesService {
	mock := &MockGenerateLoglinesService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
