// Code generated by mockery v2.53.1. DO NOT EDIT.

package apimocks

import (
	context "github.com/a-novel-kit/context"
	mock "github.com/stretchr/testify/mock"

	models "github.com/a-novel/story-schematics/models"

	services "github.com/a-novel/story-schematics/internal/services"
)

// MockCreateStoryPlanService is an autogenerated mock type for the CreateStoryPlanService type
type MockCreateStoryPlanService struct {
	mock.Mock
}

type MockCreateStoryPlanService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateStoryPlanService) EXPECT() *MockCreateStoryPlanService_Expecter {
	return &MockCreateStoryPlanService_Expecter{mock: &_m.Mock}
}

// CreateStoryPlan provides a mock function with given fields: ctx, request
func (_m *MockCreateStoryPlanService) CreateStoryPlan(ctx context.Context, request services.CreateStoryPlanRequest) (*models.StoryPlan, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateStoryPlan")
	}

	var r0 *models.StoryPlan
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, services.CreateStoryPlanRequest) (*models.StoryPlan, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, services.CreateStoryPlanRequest) *models.StoryPlan); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.StoryPlan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, services.CreateStoryPlanRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCreateStoryPlanService_CreateStoryPlan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateStoryPlan'
type MockCreateStoryPlanService_CreateStoryPlan_Call struct {
	*mock.Call
}

// CreateStoryPlan is a helper method to define mock.On call
//   - ctx context.Context
//   - request services.CreateStoryPlanRequest
func (_e *MockCreateStoryPlanService_Expecter) CreateStoryPlan(ctx interface{}, request interface{}) *MockCreateStoryPlanService_CreateStoryPlan_Call {
	return &MockCreateStoryPlanService_CreateStoryPlan_Call{Call: _e.mock.On("CreateStoryPlan", ctx, request)}
}

func (_c *MockCreateStoryPlanService_CreateStoryPlan_Call) Run(run func(ctx context.Context, request services.CreateStoryPlanRequest)) *MockCreateStoryPlanService_CreateStoryPlan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(services.CreateStoryPlanRequest))
	})
	return _c
}

func (_c *MockCreateStoryPlanService_CreateStoryPlan_Call) Return(_a0 *models.StoryPlan, _a1 error) *MockCreateStoryPlanService_CreateStoryPlan_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCreateStoryPlanService_CreateStoryPlan_Call) RunAndReturn(run func(context.Context, services.CreateStoryPlanRequest) (*models.StoryPlan, error)) *MockCreateStoryPlanService_CreateStoryPlan_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCreateStoryPlanService creates a new instance of MockCreateStoryPlanService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateStoryPlanService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateStoryPlanService {
	mock := &MockCreateStoryPlanService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
