// Code generated by mockery v2.53.1. DO NOT EDIT.

package apimocks

import (
	context "github.com/a-novel-kit/context"
	mock "github.com/stretchr/testify/mock"

	models "github.com/a-novel/story-schematics/models"

	services "github.com/a-novel/story-schematics/internal/services"
)

// MockExpandLoglineService is an autogenerated mock type for the ExpandLoglineService type
type MockExpandLoglineService struct {
	mock.Mock
}

type MockExpandLoglineService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExpandLoglineService) EXPECT() *MockExpandLoglineService_Expecter {
	return &MockExpandLoglineService_Expecter{mock: &_m.Mock}
}

// ExpandLogline provides a mock function with given fields: ctx, request
func (_m *MockExpandLoglineService) ExpandLogline(ctx context.Context, request services.ExpandLoglineRequest) (*models.LoglineIdea, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for ExpandLogline")
	}

	var r0 *models.LoglineIdea
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, services.ExpandLoglineRequest) (*models.LoglineIdea, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, services.ExpandLoglineRequest) *models.LoglineIdea); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.LoglineIdea)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, services.ExpandLoglineRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExpandLoglineService_ExpandLogline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExpandLogline'
type MockExpandLoglineService_ExpandLogline_Call struct {
	*mock.Call
}

// ExpandLogline is a helper method to define mock.On call
//   - ctx context.Context
//   - request services.ExpandLoglineRequest
func (_e *MockExpandLoglineService_Expecter) ExpandLogline(ctx interface{}, request interface{}) *MockExpandLoglineService_ExpandLogline_Call {
	return &MockExpandLoglineService_ExpandLogline_Call{Call: _e.mock.On("ExpandLogline", ctx, request)}
}

func (_c *MockExpandLoglineService_ExpandLogline_Call) Run(run func(ctx context.Context, request services.ExpandLoglineRequest)) *MockExpandLoglineService_ExpandLogline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(services.ExpandLoglineRequest))
	})
	return _c
}

func (_c *MockExpandLoglineService_ExpandLogline_Call) Return(_a0 *models.LoglineIdea, _a1 error) *MockExpandLoglineService_ExpandLogline_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExpandLoglineService_ExpandLogline_Call) RunAndReturn(run func(context.Context, services.ExpandLoglineRequest) (*models.LoglineIdea, error)) *MockExpandLoglineService_ExpandLogline_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockExpandLoglineService creates a new instance of MockExpandLoglineService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExpandLoglineService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExpandLoglineService {
	mock := &MockExpandLoglineService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
