# ======================================================================================================================
# Loglines
# ======================================================================================================================
generateLoglines:
  system:
    themed: |
      List engaging and original ideas for a new fictional story, based on the user input.

      Return {{.Count}} loglines.
    random: |
      List engaging and original ideas for a new fictional story, based on random themes.

      Return {{.Count}} loglines.
expandLogline: |
  Expand on the story idea provided by the user.

# ======================================================================================================================
# Story Plan
# ======================================================================================================================
storyPlan: |
  {{.Description}}

  Here's a detailed breakdown with minimum scenes and key points for each beat:
  {{range .Beats}}
  {{.Name}} {{.GetScenesCount}}
  JSON Key: {{.Key}}
  Key points:{{range .KeyPoints}}
    - {{.}}{{end}}
  Purpose: {{.Purpose}}
  {{end}}
  This concludes the breakdown. Below are important things for you to consider.

  Focus on Essentials:
  Ensure each scene serves a clear purpose and advances the plot.

  Avoid Redundancy:
  Eliminate unnecessary scenes that don't contribute to character development or plot progression.

  Balance Pacing:
  Allocate scenes strategically to maintain engagement throughout the story.

  Character Development:
  Ensure each scene contributes to character growth and progression.

# ======================================================================================================================
# Beats Sheet
# ======================================================================================================================
generateBeatsSheet: |
  You are a writer. Create a story based on the "{{.Plan.Name}}" story plan and the logline provided by the user.

  {{.StoryPlan}}
regenerateBeats:
  system: |
    You are a writer. You write stories based on the "{{.Plan.Name}}" story plan.

    {{.StoryPlan}}
  input1: |
    Create a story based on the following logline:

    {{.Logline}}
  input2: |
    Generate the missing content for the following beats, in JSON format. Return ONLY the missing beats, in the
    same order as the story plan.
    {{range .Beats}}
    - {{.}}{{end}}

# ======================================================================================================================
# Beat
# ======================================================================================================================
expandBeat:
  system: |
    You are a writer that uses the "{{.Plan.Name}}" story plan to create stories.

    {{.StoryPlan}}
  input1: |
    Create a new beats sheet for the following logline:

    {{.Logline}}
  input2: |
    Expand on the '{{.TargetKey}}' beat.
