# ======================================================================================================================
# Loglines
# ======================================================================================================================
generateLoglines:
  system:
    themed: |
      Liste des idées engageantes et originales pour une nouvelle histoire fictive, basée sur les entrées de 
      l'utilisateur.

      Retourne {{.Count}} prémisses.
    random: |
      Liste des idées engageantes et originales pour une nouvelle histoire fictive, basée sur des thèmes aléatoires.

      Retourne {{.Count}} prémisses.
expandLogline: |
  Développe l'idée d'histoire fournie par l'utilisateur.

# ======================================================================================================================
# Story Plan
# ======================================================================================================================
storyPlan: |
  {{.Description}}

  Voici une analyse détaillée avec un minimum de scènes et des points clés pour chaque battement:
  {{range .Beats}}
  {{.Name}} {{.GetScenesCount}}
  JSON Key: {{.Key}}
  Battements:{{range .KeyPoints}}
    - {{.}}{{end}}
  Objectif: {{.Purpose}}
  {{end}}
  Ceci conclut l'analyse. Voici les points importants à considérer.

  Focalises toi sur l'essentiel:
  Assure-toi que chaque scène a un but clair et fait avancer l'intrigue.

  Évite la redondance:
  Élimine les scènes inutiles qui ne contribuent pas au développement des personnages ou à la progression de l'intrigue.

  Équilibre le rythme:
  Alloue les scènes de manière stratégique pour maintenir l'engagement tout au long de l'histoire.

  Fais évoluer les personnages:
  Assure-toi que chaque scène contribue à la croissance et à la progression des différents personnages.

# ======================================================================================================================
# Beats Sheet
# ======================================================================================================================
generateBeatsSheet: |
  Tu es un écrivain. Crée une histoire basée sur le plan d'histoire "{{.Plan.Name}}" et la prémisse fournie par 
  l'utilisateur.

  {{.StoryPlan}}
regenerateBeats:
  system: |
    Tu es un écrivain. Tu écris des histoires basées sur le plan d'histoire "{{.Plan.Name}}".

    {{.StoryPlan}}
  input1: |
    Crée une histoire basée sur la prémisse suivante:

    {{.Logline}}
  input2: |
    Génère les battements manquants suivant, au format JSON. Retourne UNIQUEMENT les battements manquants, dans
    le même ordre que le plan d'histoire.
    {{range .Beats}}
    - {{.}}{{end}}

# ======================================================================================================================
# Beat
# ======================================================================================================================
expandBeat:
  system: |
    Tu es un écrivain qui utilise le plan d'histoire "{{.Plan.Name}}" pour créer des histoires.

    {{.StoryPlan}}
  input1: |
    Génère une nouvelle fiche de battements pour la prémisse suivante:

    {{.Logline}}
  input2: |
    Développe le battement '{{.TargetKey}}'.
