name: auto-assign author
on:
  pull_request:
    types: [opened, reopened]

jobs:
  assign-author:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    if: ${{ github.event.pull_request.user.login != vars.DEPENDENCY_BOT_LOGIN }}
    steps:
      - uses: a-novel-kit/workflows/generic-actions/assign-bot@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
