name: release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: a-novel-kit/workflows/publish-actions/auto-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  api-build:
    needs: [release]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    services:
      postgres:
        image: postgres:17-alpine
        ports:
          - "5433:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
    env:
      DSN: postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable
      GROQ_TOKEN: ${{ secrets.GROQ_TOKEN }}
    steps:
      - uses: a-novel-kit/workflows/build-actions/docker-rest-api@master
        with:
          file: build/api.Dockerfile
          image_name: ${{ github.repository }}/api
          github_token: ${{ secrets.GITHUB_TOKEN }}
          run_args: -e DSN="${DSN}" -e MASTER_KEY="${MASTER_KEY}"
