name: self-approve admin

on:
  workflow_dispatch:
    inputs:
      pr:
        description: The pull request number to approve
        required: true
        type: number

permissions:
  contents: write
  pull-requests: write

jobs:
  approve-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: a-novel-kit/workflows/generic-actions/approve-bot@master
        with:
          pull_request: "https://github.com/${{ github.event.organization.login }}/${{ github.event.repository.name }}/pull/${{ inputs.pr }}"
          github_token: ${{ secrets.GITHUB_TOKEN }}
